"""adding discount column

Revision ID: 5fa3576f4e6d
Revises: cf8bf1aa17b3
Create Date: 2024-10-15 19:30:40.740167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fa3576f4e6d'
down_revision = 'cf8bf1aa17b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_details', schema=None) as batch_op:
        batch_op.drop_column('discount')

    # ### end Alembic commands ###
